// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1mB34U-nvDFSSCsQo_aw_bT-msDSmnw',
    appId: '1:403843802264:web:930465281c8824de7a1ced',
    messagingSenderId: '403843802264',
    projectId: 'internet-of-things-97930',
    authDomain: 'internet-of-things-97930.firebaseapp.com',
    databaseURL: 'https://internet-of-things-97930-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internet-of-things-97930.firebasestorage.app',
    measurementId: 'G-TJV26ZM7WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkgM0z65Z8GdUzT7tSBWcBVS-ka67S8SM',
    appId: '1:403843802264:android:efa03fd6d82b460e7a1ced',
    messagingSenderId: '403843802264',
    projectId: 'internet-of-things-97930',
    databaseURL: 'https://internet-of-things-97930-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internet-of-things-97930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkWExZj57ouGbwUKaDsPpsrwb1DtNJm58',
    appId: '1:403843802264:ios:5eeefe9f2f60f6f47a1ced',
    messagingSenderId: '403843802264',
    projectId: 'internet-of-things-97930',
    databaseURL: 'https://internet-of-things-97930-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internet-of-things-97930.firebasestorage.app',
    iosClientId: '403843802264-hffl5glmdcll1qdv9dkm8gp69olcrb2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkWExZj57ouGbwUKaDsPpsrwb1DtNJm58',
    appId: '1:403843802264:ios:5eeefe9f2f60f6f47a1ced',
    messagingSenderId: '403843802264',
    projectId: 'internet-of-things-97930',
    databaseURL: 'https://internet-of-things-97930-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internet-of-things-97930.firebasestorage.app',
    iosClientId: '403843802264-hffl5glmdcll1qdv9dkm8gp69olcrb2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW1mB34U-nvDFSSCsQo_aw_bT-msDSmnw',
    appId: '1:403843802264:web:c449f29a3945ab437a1ced',
    messagingSenderId: '403843802264',
    projectId: 'internet-of-things-97930',
    authDomain: 'internet-of-things-97930.firebaseapp.com',
    databaseURL: 'https://internet-of-things-97930-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internet-of-things-97930.firebasestorage.app',
    measurementId: 'G-QHZN48KVWB',
  );

}